import { Sparkles } from 'lucide-react';
import { CAMERA_STATES, SCREEN_CATEGORIES } from '../../utils/constants.js';
import { formatMinutes, formatTime } from '../../utils/formatters.js';
import PanelHeader from '../common/PanelHeader.jsx';

const categoryInfo = (key) => SCREEN_CATEGORIES[key] ?? SCREEN_CATEGORIES.other;
const cameraInfo = (key) => CAMERA_STATES[key] ?? CAMERA_STATES.other;

/** Time per webcam state from camera-agent. Labels only: there are no camera images to show. */
function CameraPanel({ camera }) {
  const states = Object.entries(camera.stateMinutes).sort(([, a], [, b]) => b - a);
  const total = states.reduce((sum, [, minutes]) => sum + minutes, 0);
  const top = states[0]?.[1] ?? 0;
  return (
    <article className="panel">
      <PanelHeader
        title="At the desk (camera)"
        subtitle={`${formatMinutes(camera.atDeskMinutes)} at the desk · ${formatMinutes(camera.awayMinutes)} away · ${camera.observationCount} checks`}
      />
      <ul className="app-usage">
        {states.map(([key, minutes]) => (
          <li key={key}>
            <span>{cameraInfo(key).label}</span>
            <span className="muted">{total ? Math.round((minutes / total) * 100) : 0}%</span>
            <div className="progress progress-wide" role="presentation">
              <span className={`bar-${cameraInfo(key).tone}`} style={{ width: `${(minutes / top) * 100}%` }} />
            </div>
            <strong>{formatMinutes(minutes)}</strong>
          </li>
        ))}
      </ul>
      <p className="muted">From webcam checks the person turned on in the camera agent. Only generic labels are kept, never images. Breaks and time away are a normal part of the day.</p>
    </article>
  );
}

export default function DailyAnalysisView({ analysis }) {
  const categories = Object.entries(analysis.categoryMinutes).sort(([, a], [, b]) => b - a);
  const total = categories.reduce((sum, [, minutes]) => sum + minutes, 0);
  const top = categories[0]?.[1] ?? 0;

  return (
    <>
      <section className="content-grid">
        <article className="panel">
          <PanelHeader title="Summary" subtitle={`${analysis.analyzedCount} of ${analysis.screenshotCount} screenshots analysed`} />
          <p className="report-summary">{analysis.summary}</p>
          {analysis.highlights.length > 0 && (
            <div className="report-card">
              <h4>Highlights</h4>
              <ul>{analysis.highlights.map((item) => <li key={item}>{item}</li>)}</ul>
            </div>
          )}
          {analysis.suggestions.length > 0 && (
            <div className="report-card">
              <h4>Suggestions</h4>
              <ul>{analysis.suggestions.map((item) => <li key={item}>{item}</li>)}</ul>
            </div>
          )}
          <footer className="report-footer">
            <Sparkles size={13} aria-hidden="true" />
            <span>
              {analysis.model === 'demo-sample'
                ? 'Sample data created for the demo, not a real analysis.'
                : `AI-generated by the analysis agent${analysis.model ? ` (${analysis.model})` : ''} from screen categories${analysis.camera?.observationCount ? ', camera labels' : ''} and activity totals. Review before acting on it.`}
            </span>
          </footer>
        </article>

        <article className="panel">
          <PanelHeader title="Where the time went" subtitle={`${formatMinutes(total)} observed · ${formatMinutes(analysis.productiveMinutes)} productive`} />
          {categories.length === 0 && <p className="muted">No screenshots were analysed for this day.</p>}
          <ul className="app-usage">
            {categories.map(([key, minutes]) => (
              <li key={key}>
                <span>{categoryInfo(key).label}</span>
                <span className="muted">{total ? Math.round((minutes / total) * 100) : 0}%</span>
                <div className="progress progress-wide" role="presentation">
                  <span className={`bar-${categoryInfo(key).tone}`} style={{ width: `${(minutes / top) * 100}%` }} />
                </div>
                <strong>{formatMinutes(minutes)}</strong>
              </li>
            ))}
          </ul>
        </article>
      </section>

      {analysis.camera?.observationCount > 0 && <CameraPanel camera={analysis.camera} />}

      {analysis.timeline.length > 0 && (
        <article className="panel">
          <PanelHeader title="Timeline" subtitle="One entry per screenshot, labelled by the analysis agent." />
          <ol className="timeline">
            {analysis.timeline.map((entry) => (
              <li key={entry.capturedAt}>
                <time dateTime={entry.capturedAt}>{formatTime(entry.capturedAt)}</time>
                <span className={`category-chip chip-${categoryInfo(entry.category).tone}`}>{categoryInfo(entry.category).label}</span>
                <span>{entry.activity}</span>
              </li>
            ))}
          </ol>
        </article>
      )}
    </>
  );
}
